version: 1
disable_existing_loggers: false
formatters:
  default_formatter:
    format: "[%(asctime)s] [%(name)s] %(message)s"
    datefmt: "%d/%b/%Y %H:%M:%S"
filters:
  rate_limiter:
    "()": log_rate_limit.StreamRateLimitFilter
    "period_sec": 30
handlers:
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: default_formatter
    filters:
    - rate_limiter
loggers:
  ntpi_screen:
    handlers:
    - console
    level: DEBUG
    propagate: false
root:
    handlers:
    - console
    level: DEBUG